SELECT F.FLAVOR
FROM FIRST_HALF F
JOIN (SELECT FLAVOR, SUM(TOTAL_ORDER) TOTAL_ORDER
      FROM JULY
      GROUP BY FLAVOR
     ) B
     ON F.FLAVOR=B.FLAVOR
ORDER BY (F.TOTAL_ORDER+B.TOTAL_ORDER) DESC LIMIT 3;